/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplojpa;

import java.awt.Color;
import java.awt.Component;
import java.util.List;
import javax.swing.JOptionPane;
import model.Login;
import model.Perfil;

/**
 *
 * @author alunos
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    
    Component center;
    DAO dao;
    public TelaPrincipal() {
        
        initComponents();
        setLocationRelativeTo(center);
        dao = new DAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jpfSenha = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jlEsqueciASenha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MathJax_Math", 0, 48)); // NOI18N
        jLabel1.setText("Profile Now");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 33, 311, 75));

        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 100, -1));

        jButton2.setText("Registrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        jLabel2.setText("E-mail:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jtfEmail.setBackground(new java.awt.Color(0, 0, 0));
        jtfEmail.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jtfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 126, 100, -1));

        jpfSenha.setBackground(new java.awt.Color(0, 0, 0));
        jpfSenha.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jpfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 100, -1));

        jLabel3.setText("Senha:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 163, -1, -1));

        jlEsqueciASenha.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlEsqueciASenha.setText("Esqueci a senha");
        jlEsqueciASenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlEsqueciASenhaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlEsqueciASenhaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlEsqueciASenhaMouseExited(evt);
            }
        });
        getContentPane().add(jlEsqueciASenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlEsqueciASenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlEsqueciASenhaMouseEntered
        this.jlEsqueciASenha.setForeground(new Color(51, 74, 174));
        jlEsqueciASenha.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        
        
    }//GEN-LAST:event_jlEsqueciASenhaMouseEntered

    private void jlEsqueciASenhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlEsqueciASenhaMouseExited
        this.jlEsqueciASenha.setForeground(new Color(51,51, 51));
        jlEsqueciASenha.setFont(new java.awt.Font("Dialog", 0, 12)); 
    }//GEN-LAST:event_jlEsqueciASenhaMouseExited

    private void jlEsqueciASenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlEsqueciASenhaMouseClicked
        
        new SeFodeu().setVisible(true);
        
    }//GEN-LAST:event_jlEsqueciASenhaMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Registrar(dao).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<Perfil> findPerfilEntities = dao.getPerfilDAO().findPerfilEntities();
        boolean emailSenhaCorreto = true;
        for (final Perfil p : findPerfilEntities) {
            if ( (this.jtfEmail.getText().equals(p.getLogin().getEmail())) && (this.jpfSenha.getText().equals(p.getLogin().getSenha())) ) {
                new Home(p, dao).setVisible(true);
                emailSenhaCorreto = false;
                break;
            }
        
        }
        if (emailSenhaCorreto) {
            JOptionPane.showMessageDialog(center, "Senha ou Email incorretos", "Falha ao entrar", JOptionPane.ERROR_MESSAGE);
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jlEsqueciASenha;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtfEmail;
    // End of variables declaration//GEN-END:variables
}
